package com.apiscall.skeletoncode.workpermitmodule.presentation.home

// This file is auto-generated by Safe Args

import android.os.Bundle
import androidx.core.os.bundleOf
import androidx.navigation.NavDirections
import androidx.savedstate.SavedState
import com.apiscall.skeletoncode.R

class HomeFragmentDirections private constructor() {

    data class ActionHomeFragmentToMyPermitsFragment(
        val permitId: String? = null
    ) : NavDirections {
        override fun getActionId(): Int = R.id.action_homeFragment_to_myPermitsFragment
        override fun getArguments(): Bundle = bundleOf("permitId" to permitId)
    }

    data class ActionHomeFragmentToPendingApprovalsFragment(
        val permitId: String? = null,
        override val actionId: Int,
        override val arguments: SavedState
    ) : NavDirections {
        override fun getActionId(): Int = R.id.action_homeFragment_to_pendingApprovalsFragment
        override fun getArguments(): Bundle = bundleOf("permitId" to permitId)
    }

    data class ActionHomeFragmentToActivePermitsFragment(
        val permitId: String? = null
    ) : NavDirections {
        override fun getActionId(): Int = R.id.action_homeFragment_to_activePermitsFragment
        override fun getArguments(): Bundle = bundleOf("permitId" to permitId)
    }

    data class ActionHomeFragmentToCreatePermitFragment : NavDirections {
        override fun getActionId(): Int = R.id.action_homeFragment_to_createPermitFragment
        override fun getArguments(): Bundle = bundleOf()
    }

    data class ActionHomeFragmentToNotificationsFragment : NavDirections {
        override fun getActionId(): Int = R.id.action_homeFragment_to_notificationsFragment
        override fun getArguments(): Bundle = bundleOf()
    }

    data class ActionHomeFragmentToProfileFragment : NavDirections {
        override fun getActionId(): Int = R.id.action_homeFragment_to_profileFragment
        override fun getArguments(): Bundle = bundleOf()
    }

    data class ActionHomeFragmentToQrScanFragment : NavDirections {
        override fun getActionId(): Int = R.id.action_homeFragment_to_qrScanFragment
        override fun getArguments(): Bundle = bundleOf()
    }

    data class ActionHomeFragmentToSearchFilterFragment : NavDirections {
        override fun getActionId(): Int = R.id.action_homeFragment_to_searchFilterFragment
        override fun getArguments(): Bundle = bundleOf()
    }

    companion object {
        fun actionHomeFragmentToPermitDetailsFragment(permitId: String): NavDirections {
            return ActionHomeFragmentToPermitDetailsFragment(permitId)
        }
    }
}